function installRecordIdentity(){
 const R=RecordModel,$=id=>document.getElementById(id);
 const originalNew=createNewSampleObj;createNewSampleObj=function(title){const sample=originalNew(title);sample.sampleData.record_identity=R.fresh(typeof currentSessionId==='string'?currentSessionId:null,sample.sampleData);return sample;};
 const originalSession=createNewSessionObj;createNewSessionObj=function(overrides={}){const result=originalSession(overrides);if(overrides.grindSize&&result.condition_provenance)result.condition_provenance.grindSize.source='manual';if(!overrides.samples)for(const sample of result.samples)if(sample.sampleData.record_identity)sample.sampleData.record_identity.session_id=result.id;return result;};
 function render(d){const r=d.record_identity;$('recordIdentitySummary').textContent=r?`로트: ${r.lot_id||'미확인'} · 평가: ${r.evaluation_id} · ${r.status==='confirmed'?'로트 확인됨':r.status==='copy-draft'?'복제 초안 · 실제 재평가 아님':'새 기록 · 로트 세부 미확인'}`:'과거 기록 · 농장/로트/평가 식별 미확인. 이름만으로 기존 로트에 합치지 않습니다.';$('identityFarmId').value=r?.farm_id||'';$('identityProducerId').value=r?.producer_id||'';$('identityCropYear').value=r?.crop_year??'';$('identityRoastBatchId').value=r?.roast_batch_id||'';$('recordIdentityDetails').textContent=r?`가공: ${r.process||'미확인'}\n원 평가 세션 ID: ${r.session_id||'미확인'}\n재커핑 원 평가: ${r.recupping_of||'없음'}\n복제 원 평가: ${r.copied_from||'없음'}\n원문 별칭: ${JSON.stringify(r.aliases)}`:'기존 커피명·농장명·수확연도 원문·로트번호는 그대로 보존합니다.';}
 const originalSetUI=setUIFromSample;setUIFromSample=function(d){originalSetUI(d);render(d);};
 $('confirmRecordIdentity').addEventListener('click',()=>{try{const draft=P0Production.currentDraft(),result=R.confirm(draft.sample.sampleData,{farm_id:$('identityFarmId').value,producer_id:$('identityProducerId').value,crop_year:$('identityCropYear').value,roast_batch_id:$('identityRoastBatchId').value},draft.sessionId);if(result.newLot){const data=getEmptySampleData();for(const k of ['coffeeName','origin','variety','process','roastDate','roastLevel',...GREEN_BEAN_FIELDS])if(Object.hasOwn(draft.sample.sampleData,k))data[k]=R.clone(draft.sample.sampleData[k]);data.title=(draft.sample.title||'샘플')+' · 새 로트';data.record_identity=result.identity;P0Production.appendEvaluation(data,data.title,draft.sample.sampleData.record_identity.confirmed_context);$('recordIdentityStatus').textContent='이전 평가를 유지하고 새 로트의 미평가 기록을 만들었습니다. 이전 기록의 로트 원문은 확인 당시 값으로 유지합니다.';}else{P0Production.replaceCurrentData({...draft.sample.sampleData,record_identity:result.identity});$('recordIdentityStatus').textContent='로트 식별 정보를 저장했습니다. 모르는 ID와 연도는 null로 보존합니다.';}}catch(e){$('recordIdentityStatus').textContent='적용하지 않았습니다: '+e.message;}});
 $('recuppingSampleBtn').addEventListener('click',()=>{try{const draft=P0Production.currentDraft(),source=draft.sample.sampleData,identity=R.recupping(source,draft.sessionId),data=getEmptySampleData();for(const k of ['coffeeName','origin','variety','process','roastDate','roastLevel',...GREEN_BEAN_FIELDS])if(Object.hasOwn(source,k))data[k]=R.clone(source[k]);data.title=(draft.sample.title||'샘플')+' · 재커핑';data.record_identity=identity;P0Production.appendEvaluation(data,data.title);$('recordIdentityStatus').textContent='같은 로트의 새 평가를 만들었습니다. 이전 점수·노트·개인 선호·업무 판단은 옛 기록에 남고 새 평가는 미입력입니다.';}catch(e){$('recordIdentityStatus').textContent='재커핑을 만들지 않았습니다: '+e.message;}});
 cloneSample=function(sampleId){try{const draft=P0Production.currentDraft();if(draft.sample.id!==sampleId)throw Error('현재 샘플을 먼저 선택하세요.');const data=AssessmentContextModel.copyDraft(draft.sample.sampleData);data.record_identity=R.copyDraft(data,draft.sessionId);if(data.schema_id===P0Model.SCHEMA)data.assessed_fields=Object.fromEntries(P0Model.SCORES.map(k=>[k,false]));data.title=(draft.sample.title||'샘플')+' · 복제 초안';P0Production.appendEvaluation(data,data.title);$('recordIdentityStatus').textContent='복제 초안을 만들었습니다. 복사한 점수는 새 명시 평가로 집계하지 않으며, 판단·추출 조건은 재확인 전으로 표시합니다.';}catch(e){$('recordIdentityStatus').textContent='복제하지 않았습니다: '+e.message;}};
}
