(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RecordModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const clone=x=>JSON.parse(JSON.stringify(x)),contextKeys=['coffeeName','origin','variety','farmName','harvestYear','process','lotNumber','supplierName'];
 function newId(prefix){return prefix+'_'+(typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID().replace(/-/g,''):Date.now().toString(36)+Math.random().toString(36).slice(2));}
 const cleanId=v=>v===''||v===null||v===undefined?null:String(v).trim();
 function year(raw){if(raw===''||raw===null||raw===undefined)return null;const text=String(raw);if(!/^\d{4}$/.test(text))throw Error('확인한 수확연도는 네 자리 숫자로 입력하거나 미확인으로 비워 두세요.');return Number(text);}
 function sameContext(a,b){if(!a||!b||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)||Array.isArray(b))return false;const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(k=>Object.hasOwn(b,k)&&a[k]===b[k]);}
 function context(d){return Object.fromEntries(contextKeys.map(k=>[k,String(d[k]??'')]));}
 function aliases(d){return {coffee_name:[String(d.coffeeName??'')],farm_name:[String(d.farmName??'')],lot_number:[String(d.lotNumber??'')],crop_year_text:[String(d.harvestYear??'')],process_text:[String(d.process??'')]};}
 function addAliases(before,after){const next=clone(before||{});for(const[k,values]of Object.entries(after)){next[k]=[...new Set([...(next[k]||[]),...values])];if(next[k].length>50)throw Error('별칭이 너무 많습니다. 기존 기록을 보관하고 별도 로트로 나누세요.');}return next;}
 function fresh(sessionId,d={}){return {version:1,farm_id:null,producer_id:null,lot_id:newId('lot'),crop_year:null,process:d.process||null,roast_batch_id:null,session_id:sessionId||null,evaluation_id:newId('evaluation'),recupping_of:null,copied_from:null,status:'draft',aliases:aliases(d),confirmed_context:null};}
 function validate(ref){if(ref===undefined)return;if(!ref||typeof ref!=='object'||Array.isArray(ref)||ref.version!==1)throw Error('지원하지 않는 로트·평가 식별 형식입니다.');for(const k of ['farm_id','producer_id','lot_id','roast_batch_id','session_id','evaluation_id','recupping_of','copied_from']){const v=ref[k];if(v!==null&&(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(v)))throw Error(k+'는 영문·숫자·밑줄·하이픈의 식별자 또는 null이어야 합니다.');}if(!ref.evaluation_id)throw Error('평가 ID가 필요합니다.');if(ref.crop_year!==null&&(!Number.isInteger(ref.crop_year)||ref.crop_year<1000||ref.crop_year>9999))throw Error('확인한 수확연도 또는 null이 필요합니다.');if(ref.process!==null&&(typeof ref.process!=='string'||ref.process.length>500))throw Error('가공은 문자열 또는 null이어야 합니다.');if(!['draft','confirmed','copy-draft'].includes(ref.status))throw Error('알 수 없는 식별 상태입니다.');if(ref.status==='confirmed'&&!ref.lot_id)throw Error('확인한 로트에는 ID가 필요합니다.');if(!ref.aliases||typeof ref.aliases!=='object'||Array.isArray(ref.aliases))throw Error('원문 별칭이 필요합니다.');for(const values of Object.values(ref.aliases))if(!Array.isArray(values)||values.length>50||values.some(v=>typeof v!=='string'||v.length>5000))throw Error('원문 별칭 형식이 올바르지 않습니다.');}
 function confirm(d,patch,sessionId){const old=d.record_identity,prior=old?clone(old):fresh(sessionId,d);const farm=cleanId(patch.farm_id),producer=cleanId(patch.producer_id),crop=year(patch.crop_year),process=d.process||null;const changed=!!old?.confirmed_context&&(old.farm_id!==farm||old.producer_id!==producer||old.crop_year!==crop||old.process!==process||!sameContext(old.confirmed_context,context(d)));const next={...prior,farm_id:farm,producer_id:producer,crop_year:crop,process,roast_batch_id:cleanId(patch.roast_batch_id),lot_id:changed?newId('lot'):(prior.lot_id||newId('lot')),session_id:changed?sessionId:(prior.session_id||sessionId||null),evaluation_id:changed?newId('evaluation'):prior.evaluation_id,recupping_of:changed?null:prior.recupping_of,copied_from:changed?null:prior.copied_from,status:'confirmed',aliases:addAliases(prior.aliases,aliases(d)),confirmed_context:context(d)};validate(next);return {identity:next,newLot:changed};}
 function recupping(d,sessionId){const old=d.record_identity;validate(old);if(!old||old.status!=='confirmed')throw Error('먼저 이 샘플의 로트 정보를 확인해 주세요. 과거 이름만으로 같은 로트를 추정하지 않습니다.');if(!sameContext(old.confirmed_context,context(d)))throw Error('농장·크롭·가공·로트 원문이 바뀌었습니다. 로트 정보를 다시 확인하면 새 로트 ID로 분리합니다.');return {...clone(old),session_id:sessionId,evaluation_id:newId('evaluation'),recupping_of:old.evaluation_id,copied_from:null};}
 function copyDraft(d,sessionId){const old=d.record_identity;const next=old?clone(old):fresh(sessionId,d);if(!old?.confirmed_context)next.lot_id=null;next.evaluation_id=newId('evaluation');next.session_id=sessionId;next.recupping_of=null;next.copied_from=old?.evaluation_id||null;next.status='copy-draft';validate(next);return next;}
 return {newId,fresh,validate,confirm,recupping,copyDraft,clone};
});
